hPushOAM EQU $ff80
hFF81 EQU $ff81
hFF82 EQU $ff82
hFF83 EQU $ff83
hFF84 EQU $ff84
hFF85 EQU $ff85
hFF86 EQU $ff86
hFF87 EQU $ff87
hFF88 EQU $ff88
hFF89 EQU $ff89
hFF8A EQU $ff8a
hFF8B EQU $ff8b
hFF8C EQU $ff8c
hFF8D EQU $ff8d
hFF8E EQU $ff8e
hFF8F EQU $ff8f
hFF90 EQU $ff90
hFF91 EQU $ff91
hFF92 EQU $ff92
hFF93 EQU $ff93
hFF94 EQU $ff94
hFF95 EQU $ff95
hFF96 EQU $ff96
hFF97 EQU $ff97
hFF98 EQU $ff98
hFF99 EQU $ff99
hFF9A EQU $ff9a
hFF9B EQU $ff9b
hFF9C EQU $ff9c
hFF9D EQU $ff9d
hFF9E EQU $ff9e
hFF9F EQU $ff9f
hFFA0 EQU $ffa0
hFFA1 EQU $ffa1
hSRamEnable EQU $ffa2
hROMBank EQU $ffa3
hROMBankHi EQU $ffa4
hSRAMBank EQU $ffa5
hVRAMBank EQU $ffa6
hWRAMBank EQU $ffa7
hFFA8 EQU $ffa8
hGBC EQU $ffa9
hFFAA EQU $ffaa
hLCDC EQU $ffab
hFFAC EQU $ffac
hFFAD EQU $ffad
hFFAE EQU $ffae
hFFAF EQU $ffaf
hFFB0 EQU $ffb0
hSCX EQU $ffb1
hSCY EQU $ffb2
hFFB3 EQU $ffb3
hFFB4 EQU $ffb4
hFFB5 EQU $ffb5
hFFB6 EQU $ffb6
hFFB7 EQU $ffb7
hFFB8 EQU $ffb8
hVBlankHasOccurred EQU $ffb9
hFFBA EQU $ffba
hFFBB EQU $ffbb
hFFBC EQU $ffbc
hJoyPressed EQU $ffbd
hJoyNew EQU $ffbe
hJoyRepeat EQU $ffbf
hJoyLast EQU $ffc0
hJoyHoldTimer EQU $ffc1
hJoyHoldTimerResetFirst EQU $ffc2
hJoyHoldTimerResetSubsequent EQU $ffc3

hGFXSourceAddr EQU $ffc4
hGFXSourceBank EQU $ffc6
hGFXDestAddr EQU $ffc7
hGFXDestBank EQU $ffc9
hGFXSubBlockSize EQU $ffca
hGFXBlockSize EQU $ffcc
hGFXNumBlocks EQU $ffce

hFFD0 EQU $ffd0
hFFD1 EQU $ffd1
hFFD2 EQU $ffd2
hFFD3 EQU $ffd3
hFFD4 EQU $ffd4
hFFD5 EQU $ffd5
hFFD6 EQU $ffd6
hFFD7 EQU $ffd7
hFFD8 EQU $ffd8
hFFD9 EQU $ffd9
hFFDA EQU $ffda
hFFDB EQU $ffdb
hFFDC EQU $ffdc
hFFDD EQU $ffdd
hFFDE EQU $ffde
hFFDF EQU $ffdf
hFFE0 EQU $ffe0
hFFE1 EQU $ffe1
hFFE2 EQU $ffe2
hFFE3 EQU $ffe3
hFFE4 EQU $ffe4
hFFE5 EQU $ffe5
hFFE6 EQU $ffe6
hFFE7 EQU $ffe7
hFFE8 EQU $ffe8
hFFE9 EQU $ffe9
hFFEA EQU $ffea
hFFEB EQU $ffeb
hFFEC EQU $ffec
hFFED EQU $ffed
hFFEE EQU $ffee
hFFEF EQU $ffef
hFFF0 EQU $fff0
hFFF1 EQU $fff1
hFFF2 EQU $fff2
hFFF3 EQU $fff3
hFFF4 EQU $fff4
hFFF5 EQU $fff5
hFFF6 EQU $fff6
hFFF7 EQU $fff7
hFFF8 EQU $fff8
hFFF9 EQU $fff9
hFFFA EQU $fffa
hFFFB EQU $fffb
hFFFC EQU $fffc
hFFFD EQU $fffd
hFFFE EQU $fffe
